package com.thelightphone.cdta.gtfs

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.double
import kotlinx.serialization.json.int

/**
 * Parsing the compact GTFS JSON format generated by the Python preprocessing script.
 */
object GtfsParser {

    private val json = Json { ignoreUnknownKeys = true }

    fun parse(jsonString: String): GtfsData {
        val element = json.parseToJsonElement(jsonString)
        val root = element.jsonObject

        val stops = parseStops(root["stops"]?.jsonObject ?: return GtfsData())
        val tripStops = parseTripStops(root["trip_stops"]?.jsonObject ?: return GtfsData())
        val tripTimes = parseTripTimes(root["trip_times"]?.jsonObject ?: return GtfsData())
        val tripMeta = parseTripMeta(root["trip_meta"]?.jsonObject ?: return GtfsData())
        val routeTrips = parseRouteTrips(root["route_trips"]?.jsonObject ?: return GtfsData())
        val routes = parseRoutes(root["routes"]?.jsonObject ?: return GtfsData())

        return GtfsData(
            stops = stops,
            tripStops = tripStops,
            tripTimes = tripTimes,
            tripMeta = tripMeta,
            routeTrips = routeTrips,
            routes = routes,
        )
    }

    private fun parseStops(obj: kotlinx.serialization.json.JsonObject): Map<String, GtfsStop> {
        val result = mutableMapOf<String, GtfsStop>()
        for ((id, value) in obj) {
            val arr = value.jsonArray
            if (arr.size >= 4) {
                result[id] = GtfsStop(
                    name = arr[0].jsonPrimitive.content,
                    lat = arr[1].jsonPrimitive.double,
                    lon = arr[2].jsonPrimitive.double,
                    id = arr[3].jsonPrimitive.content,
                )
            } else if (arr.size >= 3) {
                result[id] = GtfsStop(
                    name = arr[0].jsonPrimitive.content,
                    lat = arr[1].jsonPrimitive.double,
                    lon = arr[2].jsonPrimitive.double,
                    id = id,
                )
            }
        }
        return result
    }

    private fun parseTripStops(obj: kotlinx.serialization.json.JsonObject): Map<String, List<String>> {
        return obj.mapValues { (_, value) ->
            value.jsonArray.map { it.jsonPrimitive.content }
        }
    }

    private fun parseTripTimes(obj: kotlinx.serialization.json.JsonObject): Map<String, List<List<Int>>> {
        return obj.mapValues { (_, value) ->
            value.jsonArray.map { arr ->
                arr.jsonArray.map { it.jsonPrimitive.int }
            }
        }
    }

    private fun parseTripMeta(obj: kotlinx.serialization.json.JsonObject): Map<String, TripMeta> {
        return obj.mapValues { (_, value) ->
            val jo = value.jsonObject
            TripMeta(
                headsign = jo["headsign"]?.jsonPrimitive?.content ?: "",
                direction = jo["direction"]?.jsonPrimitive?.int ?: 0,
            )
        }
    }

    private fun parseRouteTrips(obj: kotlinx.serialization.json.JsonObject): Map<String, List<String>> {
        return obj.mapValues { (_, value) ->
            value.jsonArray.map { it.jsonPrimitive.content }
        }
    }

    private fun parseRoutes(obj: kotlinx.serialization.json.JsonObject): Map<String, GtfsRoute> {
        return obj.mapValues { (_, value) ->
            val jo = value.jsonObject
            GtfsRoute(
                short = jo["short"]?.jsonPrimitive?.content ?: "",
                long = jo["long"]?.jsonPrimitive?.content ?: "",
                desc = jo["desc"]?.jsonPrimitive?.content ?: "",
                color = jo["color"]?.jsonPrimitive?.content ?: "",
                textColor = jo["text_color"]?.jsonPrimitive?.content ?: "",
            )
        }
    }
}
