package com.thelightphone.cdta.gtfs

/**
 * Compact parsed GTFS data structure.
 * Fields match the JSON format generated by the Python preprocessing script.
 */
data class GtfsData(
    val stops: Map<String, GtfsStop> = emptyMap(),
    val tripStops: Map<String, List<String>> = emptyMap(),
    val tripTimes: Map<String, List<List<Int>>> = emptyMap(),
    val tripMeta: Map<String, TripMeta> = emptyMap(),
    val routeTrips: Map<String, List<String>> = emptyMap(),
    val routes: Map<String, GtfsRoute> = emptyMap(),
)

data class GtfsStop(
    val name: String,
    val lat: Double,
    val lon: Double,
    val id: String = "",
)

data class TripMeta(
    val headsign: String = "",
    val direction: Int = 0,
)

data class GtfsRoute(
    val short: String,
    val long: String,
    val desc: String,
    val color: String,
    val textColor: String,
) {
    val shortName: String get() = short
    val longName: String get() = long

    val displayName: String
        get() = longName.ifEmpty { shortName }

    val isBusPlus: Boolean
        get() = longName.contains("PLUS", ignoreCase = true) || desc.contains("BusPlus", ignoreCase = true)
}
